// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpVTkpD1w752z2NUcf1TGQ-kDzklT-s0',
    appId: '1:922590350887:web:fc4a2c69a49428d5fac802',
    messagingSenderId: '922590350887',
    projectId: 'coffee-shop-app-437c7',
    authDomain: 'coffee-shop-app-437c7.firebaseapp.com',
    storageBucket: 'coffee-shop-app-437c7.appspot.com',
    measurementId: 'G-VVBK2G9ME9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecCC2nsCpAZI5QsWe5oy8A18wlVjHnOE',
    appId: '1:922590350887:android:159ef90310b0f1e2fac802',
    messagingSenderId: '922590350887',
    projectId: 'coffee-shop-app-437c7',
    storageBucket: 'coffee-shop-app-437c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6a4WJV2n3wtnY4gtMfeqsd03xgw59qY',
    appId: '1:922590350887:ios:f6003661f360fd52fac802',
    messagingSenderId: '922590350887',
    projectId: 'coffee-shop-app-437c7',
    storageBucket: 'coffee-shop-app-437c7.appspot.com',
    androidClientId: '922590350887-1thvno8rkq1jgpdmq0cgnflfgrmoe8vk.apps.googleusercontent.com',
    iosClientId: '922590350887-lghei6tv11r0ei0f1grp5eafu30i273a.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6a4WJV2n3wtnY4gtMfeqsd03xgw59qY',
    appId: '1:922590350887:ios:f6003661f360fd52fac802',
    messagingSenderId: '922590350887',
    projectId: 'coffee-shop-app-437c7',
    storageBucket: 'coffee-shop-app-437c7.appspot.com',
    androidClientId: '922590350887-1thvno8rkq1jgpdmq0cgnflfgrmoe8vk.apps.googleusercontent.com',
    iosClientId: '922590350887-lghei6tv11r0ei0f1grp5eafu30i273a.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeshop',
  );
}
